using System;
using System.Collections.Generic;
using System.Security.Cryptography;

namespace TrayTrigger.Services;

/// <summary>
/// Checks the signature the release workflow publishes beside SHA256SUMS.txt
/// (<c>SHA256SUMS.txt.sig</c>). The manifest and the installer sit on the same GitHub release, so
/// whoever can replace one can replace the other and the hashes still agree; the signature is made
/// with a private key that is not on the release, and checked against the public keys compiled in
/// here. Releases are not Authenticode-signed, so this is the updater's only check that doesn't
/// take the release's own word for it.
///
/// ECDSA P-256 over SHA-256, signature in DER (RFC 3279) so that
/// <c>openssl dgst -sha256 -verify</c> can check it by hand - see the README.
/// </summary>
public static class ReleaseManifestVerifier
{
    /// <summary>
    /// Base64 SubjectPublicKeyInfo of every key a manifest may be signed with. The first is the
    /// release workflow's (its private half is the RELEASE_SIGNING_KEY Actions secret); the second
    /// is a backup whose private half is kept offline, so losing the secret doesn't strand
    /// installed copies. Generated by tools\ReleaseSigning. The same keys, as PEM, are in
    /// release-signing-key.pub.pem and release-signing-backup-key.pub.pem for verifying by hand.
    ///
    /// While this is empty the check is off and the updater behaves as it did before.
    /// </summary>
    internal static readonly IReadOnlyList<string> TrustedPublicKeys =
    [
        // Release workflow (RELEASE_SIGNING_KEY secret), generated 2026-09-18.
        "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEigprc2/rXdZL5iK7Jpk4h061rtddT67cWPF/T5IR0HnE2jMZ9Gj6V79MYX4TC3ZLPwFF2XynzqJQAHysf6+/2Q==",
        // Offline backup, generated 2026-09-18.
        "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKausemx62ESYbdwNWZZ/ISPsIfhpua83e1VFNi+9hhiudGtDRW4x0V8mpMkq2M+xwlaYNrV3tOa6wSdmuZWcbQ==",
    ];

    /// <summary>True once keys are compiled in: from then on an update without a valid signature is refused.</summary>
    public static bool IsEnforced => TrustedPublicKeys.Count > 0;

    /// <summary>True when <paramref name="signature"/> is a valid signature of <paramref name="manifest"/> by any trusted key.</summary>
    public static bool Verify(ReadOnlySpan<byte> manifest, ReadOnlySpan<byte> signature) =>
        Verify(manifest, signature, TrustedPublicKeys);

    internal static bool Verify(ReadOnlySpan<byte> manifest, ReadOnlySpan<byte> signature, IReadOnlyList<string> trustedPublicKeys)
    {
        if (manifest.IsEmpty || signature.IsEmpty) return false;

        foreach (string key in trustedPublicKeys)
        {
            try
            {
                using var ecdsa = ECDsa.Create();
                ecdsa.ImportSubjectPublicKeyInfo(Convert.FromBase64String(key), out _);
                if (ecdsa.VerifyData(manifest, signature, HashAlgorithmName.SHA256, DSASignatureFormat.Rfc3279DerSequence))
                {
                    return true;
                }
            }
            catch (Exception ex) when (ex is CryptographicException or FormatException)
            {
                // A malformed signature or key is a failed check, not a crash; try the next key.
                LoggingService.Verbose("Update", $"Release signature check with one key failed: {ex.Message}");
            }
        }

        return false;
    }
}
