using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;

namespace TrayTrigger.Services;

/// <summary>
/// The user's scripts folder (%AppData%\TrayTrigger\Scripts): where "New script..." writes, where
/// the Browse buttons open, and where the bundled blank templates, examples and README are
/// materialised from embedded resources. Nothing here acts on its own - a script only runs once the
/// user picks it for a game.
///
/// <para>The bundled files are TrayTrigger's, not the user's, and are rewritten from the assembly
/// whenever they differ from what this build carries. That is what makes a correction to a template
/// or an example reach someone who already has the folder; skipping existing files meant every fix
/// only ever reached fresh installs. Nothing else in the folder is touched, and "New script..."
/// names a copy after the game, so the user's own scripts are never among the files replaced. The
/// bundled files say so at the top, and none of them asks to be edited in place.</para>
/// </summary>
public class ScriptLibraryService
{
    /// <summary>Logical-name prefix set in TrayTrigger.csproj for Scripts\Library\*.</summary>
    private const string ResourcePrefix = "ScriptLibrary/";
    public const string ReadmeFileName = "README.txt";
    public const string BlankBatchFileName = "_Blank.bat";
    public const string BlankPowerShellFileName = "_Blank.ps1";

    public string ScriptsDirectory { get; }

    public ScriptLibraryService(string baseDirectory)
    {
        ScriptsDirectory = Path.Combine(baseDirectory, "Scripts");
    }

    /// <summary>File names of every bundled script and the README, as embedded in the assembly.</summary>
    public static IReadOnlyList<string> BundledFileNames()
    {
        return typeof(ScriptLibraryService).Assembly.GetManifestResourceNames()
            .Where(n => n.StartsWith(ResourcePrefix, StringComparison.Ordinal))
            .Select(n => n.Substring(ResourcePrefix.Length))
            .OrderBy(n => n, StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    /// <summary>
    /// The embedded content of one bundled file with Windows line endings, or null if there is no
    /// such resource. The repo may store these with LF; on disk they must be CRLF - cmd.exe has
    /// parsing quirks with LF-only batch files and older Notepad shows them as one line.
    /// </summary>
    public static string? ReadBundled(string fileName)
    {
        using var stream = typeof(ScriptLibraryService).Assembly.GetManifestResourceStream(ResourcePrefix + fileName);
        if (stream == null) return null;
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd().Replace("\r\n", "\n").Replace("\n", "\r\n");
    }

    /// <summary>
    /// Creates the folder and writes every bundled file that is missing or out of date, so a fix to
    /// a template or an example reaches a folder that already exists. Idempotent and never throws.
    /// Returns the names of the files written.
    ///
    /// <para>A file that differs from this build's copy is one of two things, and they are told
    /// apart by <see cref="ManifestFileName"/>, which records what was last written: still exactly
    /// as TrayTrigger left it, meaning an older bundled version, which is replaced silently; or
    /// changed since, meaning the user edited it, in which case their version is renamed to
    /// <c>&lt;name&gt;.previous</c> before the fresh copy lands. Overwriting an edit in place would
    /// destroy work with no copy and no undo, and the people who would lose it are exactly the ones
    /// who did not read the "do not edit this file" notice at the top of it.</para>
    /// </summary>
    public IReadOnlyList<string> EnsureInstalled()
    {
        var written = new List<string>();
        try
        {
            Directory.CreateDirectory(ScriptsDirectory);
            var manifest = LoadManifest();
            bool manifestChanged = false;

            foreach (string name in BundledFileNames())
            {
                string target = Path.Combine(ScriptsDirectory, name);

                string? content = ReadBundled(name);
                if (content == null) continue;
                string freshHash = Hash(content);

                if (File.Exists(target))
                {
                    string? existing = ReadOrNull(target);

                    // Already current: nothing to write, so the folder's timestamps don't churn on
                    // every start. The manifest is still brought up to date, which is what lets a
                    // folder from before this existed settle without a spurious ".previous".
                    if (existing == content)
                    {
                        if (SetManifest(manifest, name, freshHash)) manifestChanged = true;
                        continue;
                    }

                    // Ours to replace only if it is still byte for byte what we last wrote. With no
                    // record - a folder that predates the manifest - we cannot know, and the older
                    // README told people their edits here were safe, so it is kept.
                    bool stillOurs = existing != null
                        && manifest.TryGetValue(name, out string? recorded)
                        && string.Equals(recorded, Hash(existing), StringComparison.Ordinal);

                    if (!stillOurs && !SetAside(target)) continue;
                }

                File.WriteAllText(target, content);
                if (SetManifest(manifest, name, freshHash)) manifestChanged = true;
                written.Add(name);
            }

            if (manifestChanged) SaveManifest(manifest);
            if (written.Count > 0)
            {
                LoggingService.Info("Scripts", $"Scripts folder updated ({string.Join(", ", written)}): {ScriptsDirectory}");
            }
        }
        catch (Exception ex)
        {
            LoggingService.Warn("Scripts", $"Could not prepare the scripts folder {ScriptsDirectory}: {ex.Message}");
        }
        return written;
    }

    /// <summary>A file that cannot be read counts as different, so the fresh copy is written.</summary>
    private static string? ReadOrNull(string path)
    {
        try { return File.ReadAllText(path); }
        catch (Exception ex) { LoggingService.Verbose("Scripts", $"Could not read {path} to compare it: {ex.Message}"); return null; }
    }

    // ---- Keeping what the user changed ---------------------------------------------------------

    /// <summary>Where the hash of each bundled file, as last written, is kept. Not a script, so it
    /// lives beside the folder rather than in it.</summary>
    internal const string ManifestFileName = "scripts-bundled.txt";

    /// <summary>The suffix for a user's version of a bundled file, moved out of the way.</summary>
    public const string SetAsideSuffix = ".previous";

    private string ManifestPath => Path.Combine(Path.GetDirectoryName(ScriptsDirectory) ?? ScriptsDirectory, ManifestFileName);

    private static string Hash(string content)
    {
        byte[] bytes = System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(content));
        return Convert.ToHexString(bytes);
    }

    /// <summary>Name and hash per line, tab separated. A line that cannot be read is skipped: the
    /// worst a broken manifest can do is keep a file the user could have lost anyway.</summary>
    private Dictionary<string, string> LoadManifest()
    {
        var map = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        try
        {
            if (!File.Exists(ManifestPath)) return map;
            foreach (string line in File.ReadAllLines(ManifestPath))
            {
                string[] parts = line.Split('\t');
                if (parts.Length == 2 && parts[0].Length > 0) map[parts[0]] = parts[1];
            }
        }
        catch (Exception ex) { LoggingService.Verbose("Scripts", $"Could not read {ManifestPath}: {ex.Message}"); }
        return map;
    }

    private static bool SetManifest(Dictionary<string, string> map, string name, string hash)
    {
        if (map.TryGetValue(name, out string? current) && string.Equals(current, hash, StringComparison.Ordinal)) return false;
        map[name] = hash;
        return true;
    }

    private void SaveManifest(Dictionary<string, string> map)
    {
        try
        {
            File.WriteAllLines(ManifestPath, map.OrderBy(kv => kv.Key, StringComparer.OrdinalIgnoreCase)
                                                .Select(kv => kv.Key + "\t" + kv.Value));
        }
        catch (Exception ex) { LoggingService.Warn("Scripts", $"Could not write {ManifestPath}: {ex.Message}"); }
    }

    /// <summary>
    /// Renames the user's version to "&lt;name&gt;.previous", numbering it if that is taken, so the
    /// fresh copy can be written without losing it. False means it could not be moved, and the
    /// caller leaves the file alone rather than overwriting it - a stale script the user still has
    /// beats a current one they have lost.
    /// </summary>
    private static bool SetAside(string target)
    {
        try
        {
            string kept = target + SetAsideSuffix;
            for (int n = 2; File.Exists(kept) && n < 100; n++) kept = $"{target}{SetAsideSuffix}.{n}";
            if (File.Exists(kept))
            {
                LoggingService.Warn("Scripts", $"Not replacing {target}: it has been edited and there is nowhere left to keep the previous copies.");
                return false;
            }

            File.Move(target, kept);
            LoggingService.Info("Scripts", $"{Path.GetFileName(target)} had been edited. Your version is kept as {Path.GetFileName(kept)}; TrayTrigger's copy replaces it.");
            return true;
        }
        catch (Exception ex)
        {
            LoggingService.Warn("Scripts", $"Not replacing {target}: its edited copy could not be set aside ({ex.Message}).");
            return false;
        }
    }

    /// <summary>
    /// Writes the blank template matching the target's extension (.bat/.cmd or .ps1) to the
    /// given path. Returns false without touching anything if the file already exists or the
    /// extension has no template. Throws on I/O failure so the caller can show the reason.
    /// </summary>
    public static bool CreateFromBlankTemplate(string targetPath)
    {
        string ext = Path.GetExtension(targetPath).ToLowerInvariant();
        string? templateName = ext switch
        {
            ".bat" or ".cmd" => BlankBatchFileName,
            ".ps1" => BlankPowerShellFileName,
            _ => null
        };
        if (templateName == null || File.Exists(targetPath)) return false;

        string? content = ReadBundled(templateName);
        if (content == null) return false;

        string? dir = Path.GetDirectoryName(targetPath);
        if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
        File.WriteAllText(targetPath, content);
        LoggingService.Info("Scripts", $"Created {targetPath} from {templateName}.");
        return true;
    }

    /// <summary>
    /// Opens a script for editing. Never through the file's default "open" action - for a .bat
    /// that would run it. Tries the shell's "edit" verb (Notepad or whatever the user has
    /// associated), then falls back to Notepad. An executable has nothing to edit, so its folder
    /// is opened with the file selected instead.
    /// </summary>
    public static void OpenInEditor(string path)
    {
        string p = path.Trim().Trim('"');
        if (!File.Exists(p))
        {
            LoggingService.Warn("Scripts", $"Cannot open for editing, file not found: {p}");
            return;
        }

        string ext = Path.GetExtension(p).ToLowerInvariant();
        if (ext is ".exe" or ".com")
        {
            RevealInExplorer(p);
            return;
        }

        try
        {
            Process.Start(new ProcessStartInfo(p) { Verb = "edit", UseShellExecute = true });
            return;
        }
        catch (Exception ex)
        {
            LoggingService.Verbose("Scripts", $"'edit' verb unavailable for {p} ({ex.Message}); using Notepad.");
        }

        try
        {
            Process.Start(new ProcessStartInfo(SystemExecutables.Notepad, $"\"{p}\"") { UseShellExecute = true });
        }
        catch (Exception ex)
        {
            LoggingService.Warn("Scripts", $"Could not open {p} in an editor: {ex.Message}");
        }
    }

    /// <summary>Opens the scripts folder in Explorer, creating and populating it first if needed.</summary>
    public void OpenFolder()
    {
        EnsureInstalled();
        try
        {
            Process.Start(SystemExecutables.Explorer, ScriptsDirectory);
        }
        catch (Exception ex)
        {
            LoggingService.Warn("Scripts", $"Could not open the scripts folder: {ex.Message}");
        }
    }

    private static void RevealInExplorer(string path)
    {
        try
        {
            Process.Start(SystemExecutables.Explorer, $"/select,\"{path}\"");
        }
        catch (Exception ex)
        {
            LoggingService.Warn("Scripts", $"Could not reveal {path}: {ex.Message}");
        }
    }
}
