# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: stephenh678.TrayTrigger
PackageVersion: 1.6.1
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{C8E32D15-3B10-4A99-8D1F-4395A9BF41C2}_is1'
ReleaseDate: 2026-10-09
AppsAndFeaturesEntries:
- DisplayName: TrayTrigger v1.6.1
  Publisher: stephenh678
  DisplayVersion: 1.6.1
  ProductCode: '{C8E32D15-3B10-4A99-8D1F-4395A9BF41C2}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/stephenh678/TrayTrigger/releases/download/v1.6.1/TrayTrigger-v1.6.1-Setup.exe
  InstallerSha256: E3A3726294B5ADFD41BB30D47A72D3AAC9506C31A731E6552F9808667E8D7C33
ManifestType: installer
ManifestVersion: 1.12.0
