using System.IO;
using System.Text;
using TrayTrigger.Models;
using TrayTrigger.Services;

namespace TrayTrigger.Tests;

/// <summary>The SHA256SUMS.txt manifest parsing and file hashing the updater uses to verify a
/// downloaded installer before launching it.</summary>
public class UpdateChecksumTests
{
    private const string Manifest =
        "# generated by release.yml\n" +
        "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad  TrayTrigger-v1.3.9-Setup.exe\n" +
        "0000000000000000000000000000000000000000000000000000000000000000 *TrayTrigger-v1.3.9-portable.zip\r\n" +
        "\n" +
        "not-a-hash  Garbage.exe\n";

    [Fact]
    public void FindExpectedSha256_TwoSpaceFormat()
    {
        Assert.Equal(
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
            UpdateService.FindExpectedSha256(Manifest, "TrayTrigger-v1.3.9-Setup.exe"));
    }

    [Fact]
    public void FindExpectedSha256_BinaryMarkerAndCrLf()
    {
        Assert.Equal(new string('0', 64), UpdateService.FindExpectedSha256(Manifest, "TrayTrigger-v1.3.9-portable.zip"));
    }

    [Fact]
    public void FindExpectedSha256_FileNameIsCaseInsensitive_HashIsLowercased()
    {
        string upper = "BA7816BF8F01CFEA414140DE5DAE2223B00361A396177A9CB410FF61F20015AD  setup.exe";
        Assert.Equal(upper.Substring(0, 64).ToLowerInvariant(), UpdateService.FindExpectedSha256(upper, "SETUP.EXE"));
    }

    [Theory]
    [InlineData("Missing.exe")]
    [InlineData("Garbage.exe")] // listed, but the hash isn't 64 hex chars
    [InlineData("")]
    public void FindExpectedSha256_ReturnsNullWhenAbsentOrMalformed(string fileName)
    {
        Assert.Null(UpdateService.FindExpectedSha256(Manifest, fileName));
    }

    [Fact]
    public void FindExpectedSha256_EmptyManifest()
    {
        Assert.Null(UpdateService.FindExpectedSha256("", "x.exe"));
        Assert.Null(UpdateService.FindExpectedSha256("   \n", "x.exe"));
    }

    [Fact]
    public async Task ComputeSha256Async_MatchesKnownVector()
    {
        string path = Path.Combine(Path.GetTempPath(), "TrayTriggerChecksumTest_" + Guid.NewGuid().ToString("N"));
        try
        {
            await File.WriteAllBytesAsync(path, Encoding.ASCII.GetBytes("abc"));
            Assert.Equal(
                "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
                await UpdateService.ComputeSha256Async(path));
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Fact]
    public void ChecksumsAsset_FindsManifestByNameOnly()
    {
        var release = new GitHubReleaseInfo
        {
            Assets =
            {
                new GitHubReleaseAsset { Name = "TrayTrigger-v1.3.9-Setup.exe" },
                new GitHubReleaseAsset { Name = "sha256sums.txt" },
            }
        };
        Assert.Equal("sha256sums.txt", release.ChecksumsAsset?.Name);
        Assert.Null(new GitHubReleaseInfo().ChecksumsAsset);
    }
}
